@echo off
REM Start EDMS services in manual deployment mode
echo Starting EDMS services (manual deployment)...

REM Check if SSL certificate exists or will be generated by mkcert.exe
set "FRONTEND_URL=http://localhost:5173"
if exist "%~dp0localhost+2.pem" set "FRONTEND_URL=https://localhost:5173"
if exist "%~dp0mkcert.exe" set "FRONTEND_URL=https://localhost:5173"

REM Start backend in new window
start "EDMS Backend" cmd /k "%~dp0\backend_start.bat"

REM Wait a moment for backend to start
timeout /t 3 /nobreak >nul

REM Start frontend in new window  
start "EDMS Frontend" cmd /k "%~dp0\frontend_start.bat"

echo Both services are starting in separate windows...
echo Frontend will be available at: %FRONTEND_URL%
echo Backend API is running at: http://127.0.0.1:5000
pause